# Ref: https://github.com/actions/starter-workflows/blob/main/ci/python-app.yml
# step:
# 1. runner start empty, get the code first
# 2. install uv
# 3. uv sync --locked
# 4. run ruff check
# 5. run ruff format
# 6. pyrefly check
# 7. pytest

name: ci 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7  # clone repo to runner
    - uses: astral-sh/setup-uv@v10.2.0 # install uv
      with: 
        enable-cache: true
    - run: uv sync --locked
    - run: uv run ruff check . 
    - run: uv run ruff format --check .
    - run: uv run pyrefly check
    - run: uv run pytest
